### ISSUE TITLE
Error using save

### ISSUE THREAD

**Issue by AnthoineResea** [InverseTampere/TreeQSM#11]
I experience the following error:

```
Error using save
Cannot create 'QSM_tree_t1_m1.mat' because 'results' does not exist.

Error in treeqsm (line 469)
          save(['results/QSM_',str],'QSM')

Error in Untitled2 (line 12)
QSM = treeqsm(P, inputs);
```

What is this related to?

**Comment by zoeschindler** [comment]
Did you create a folder named "results" in your working directory? I think TreeQSM only works if you manually create the folder in your working environment.

**Comment by NinhGhoster** [comment]
> I experience the following error:
> 
> ```
> Error using save
> Cannot create 'QSM_tree_t1_m1.mat' because 'results' does not exist.
> 
> Error in treeqsm (line 469)
>           save(['results/QSM_',str],'QSM')
> 
> Error in Untitled2 (line 12)
> QSM = treeqsm(P, inputs);
> ```
> 
> What is this related to?

I think this might relate to point cloud data since the algorithm can't detect a comprehensive tree shape to plot. Some trees gave me this error, some did not
