### ISSUE TITLE
How are volumes calculated?

### ISSUE THREAD

**Issue by AnthoineResea** [InverseTampere/TreeQSM#12]
I read the manual, but I'm still not 100% sure how volumes are calculated.

On page 13 there are some references to convex hull and alpha-shape algorithms to calculate the crown volume.

Anyway, are volumes of branches and trunk calculated as the sum oh the volume of each cylinder which simulates the part of the tree taken into account?

Thanls

**Comment by zoeschindler** [comment]
> convex hull and alpha-shape

These volumes are calculated using simulated points on the cylinder surfaces.

> Anyway, are volumes of branches and trunk calculated as the sum of the volume of each cylinder which simulates the part of the tree taken into account?

Yes. `TrunkVolume` is the summed volume of the cylinders belonging to the stem and `BranchVolume` is the volume of all remaining cylinders.
