### ISSUE TITLE
stand alone application

### ISSUE THREAD

**Issue by petrasvestartas** [InverseTampere/TreeQSM#2]
Hi,

I am really interested in you work and reconstructing cylindrical branches from fairly simple straight and forked beams. The video is amazing:
https://www.youtube.com/watch?v=j0Emjwp-fmU

The problem is that I am working in C# or Python.

Is there any way to use your software in these languages or as a standalone application?

**Comment by peltokukka** [comment]
Hi,

Thank you for your interest in TreeQSM. However, the problem you are describing has nothing to do specifically with TreeQSM. Rather you are wondering how to call Matlab programs with other programming languages. There are plenty of guides for such things. Regarding TreeQSM, it has been discussed whether a native python version should be created, but that is still long way off.
